regress: fuzz: change check1fuzz to send stderr to /dev/null
And also be less verbose when the test fails.

Signed-off-by: Ian Jackson <ijackson@chiark.greenend.org.uk>

diff --git a/regress/check1fuzz b/regress/check1fuzz
--- a/regress/check1fuzz
+++ b/regress/check1fuzz
@@ -26,6 +26,14 @@ case "$program" in
 *)	program="./$program" ;;
 esac
 
-${program} <"$fuzzfile" >/dev/null
+set +e
+${program} <"$fuzzfile" >/dev/null 2>&1
+rc=$?
+set -e
+
+if [ $rc != 0 ]; then
+	printf >&2 '\nFAIL-%s\n' $fuzzfile
+	exit $rc
+fi
 
 printf "$desc "
